### ISSUE TITLE
it should not be comitted.

### ISSUE THREAD

**Issue by jjalonso** [dalbar/phaser-js-starter#1]
Hi.

had to delete the comitted package-lock.json to be able to run npm install 
and also i saw your .idea folder was comitted too (you using IntelliJ  ide probably)

solved.

**Comment by dalbar** [comment]
Hello,

I have mistakenly committed the .idea folder. It has been removed in the latest commit. Thank you for your help.

**Comment by jjalonso** [comment]
Hi, thanks,

The package-lock.json was not allowing me to run npm install neither, until
removed.
Should it be removed too?

**Comment by dalbar** [comment]
The package-lock.json is making sure that every npm Installation follows the same dependency tree. Therefore, it should be committed. However, I have removed it in the last commit to avoid further problems. Can you recall the error message?
